export const SlidersData = [
  {
    id: 1,
    slide: [
      {
        slideImg:
          "https://image.uniqlo.com/UQ/ST3/vn/imagesother/AIRism/AIRismPCEn.mp4",
        type: "video",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/resadecfbdfc8449e41b7f81d2eacbc0874fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res83ddfada1c4d12778fd3e9c6f06ac516fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res9817fd1e0b6af5b6b81b379fc80d8e4afr.jpg",
        type: "image",
      },
    ],
    category: "",
    title: "What is AIRism?",
    desc: "",
  },
  {
    id: 2,
    slide: [
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/resabbfae7f010d682347195ec0b219ce93fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res41989fbf916eaeed6d27e29ab391bd07fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res9187abf938fd30a60ab3f9ce4d7df952fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res865dcb877476595e98469ebd85542bcffr.jpg",
        type: "image",
      },
    ],
    category: "Grand Opening 22 Apr, 2022",
    title: "UNIQLO SAIGON CENTER",
    desc: "Toghether We Evolve",
  },
  {
    id: 3,
    slide: [
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res698c46c162de59e79818c8e94c86c20cfr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res7e20c138995d699602597ce0845009c8fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/resb14f3cabe0357211c8c4f3590421d018fr.jpg",
        type: "image",
      },
      {
        slideImg:
          "https://im.uniqlo.com/global-cms/spa/res3041faeb8dd31bd08665bbbc96128b78fr.jpg",
        type: "image",
      },
    ],
    category: "Special Collaboration",
    title: "UNIQLO x Theory",
    desc: "Bringing sophistication to everyday life. 2nd Collection available on 29 April",
  },
];

export const CategoriesWomen = {
  columns: [
    [
      {
        title: "TOPS",
        list: [
          "Tops Colection",
          "T-Shirt",
          "UT(Graphic T-Shirts)",
          "Shirts & Blouses",
          "Sweaters",
          "Cardigans",
          "Sweat Collections",
        ],
      },
      {
        title: "DRESSES & JUMPSUITS",
        list: ["Dresses & Jumpsuits"],
      },
      {
        title: "MATERNITY",
        list: ["Maternity"],
      },
    ],
    [
      {
        title: "SPORT UTILITY WEAR",
        list: ["Sport Utility Wear"],
      },
      {
        title: "LOUNGEWEAR",
        list: [
          "Loungewear Colections",
          "Loungewear & Pajamas",
          "Relaco",
          "Bedding",
          "Room Shoes",
          "Home Accessories",
        ],
      },
    ],
    [
      {
        title: "INNERWEAR",
        list: [
          "Innerwear Collections",
          "Wireless Bras",
          "Bra Tops",
          "AISism",
          "Undershirts",
          "Underwear",
          "HEATTECH",
          "Leggings & Tights",
          "Socks",
        ],
      },
      {
        title: "BOTTOMS",
        list: [
          "Bottoms Colections",
          "Shorts",
          "Jeans",
          "Casual Pants",
          "Ankie & Cropped Pants",
          "Skirts",
        ],
      },
    ],
    [
      {
        title: "OUTERWEAR",
        list: ["Outeewear Collections", "Coats", "Blouson & Hoodie", "Jackets"],
      },
      {
        title: "ACSESSORIES",
        list: [
          "Accessories Collections",
          "AIRism Marks",
          "Hats & Beanies",
          "Bags",
          "Umbrellas",
          "Belts",
          "Shoes & Boots",
          "Fashion Glasses",
          "Others",
        ],
      },
    ],
  ],
  featured: [
    {
      title: "Featured",
      list: [
        "New Arrivals",
        "Limited Offer",
        "Comming Soon",
        "Featured News",
        "UT Graphic T-Shirts",
        "Styling Book",
        "About LifeWear",
      ],
    },
    {
      title: "Special collaboration",
      list: [
        "UNIQLO x Theory",
        "UNIQLO and JW ANDERSON",
        "+ J",
        "INES DE LA FRESSANGE",
        "Uniqlo U",
        "HANA TAJIMA FOR UNIQLO",
        "Uniqlo and Mame Kurogouchi",
      ],
    },
    {
      title: "Browse",
      list: ["All Women"],
    },
  ],
};

export const CategoriesMen = {
  columns: [
    [
      {
        title: "TOPS",
        list: [
          "Tops Colection",
          "T-Shirt",
          "UT(Graphic T-Shirts)",
          "Polo Shirts",
          "Formal Shirts",
          "Sweaters",
          "Sweat Collections",
        ],
      },
      {
        title: "LOUNGEWEAR",
        list: ["Loungewear Colections", "Loungewear & Pajamas", "Room Shoes"],
      },
    ],
    [
      {
        title: "OUTERWEAR",
        list: [
          "Outeewear Collections",
          "Coats",
          "Blouson & Hoodie",
          "Jackets",
          "Untra Light Jackets",
        ],
      },
      {
        title: "ACSESSORIES",
        list: [
          "Accessories Collections",
          "AIRism Marks",
          "Bags",
          "Umbrellas",
          "Sunglasses",
          "Hats & Beanies",
          "Belts",
          "Shoes",
          "Others",
        ],
      },
    ],
    [
      {
        title: "BOTTOMS",
        list: [
          "Bottoms Colections",
          "Shorts",
          "Chinos",
          "Jeans",
          "Easy Pants",
          "Ankle Pants",
          "Trousers",
          "Untra Light Pants",
        ],
      },
      {
        title: "SPORT UTILITY WEAR",
        list: ["Sport Utility Wear"],
      },
    ],
    [
      {
        title: "INNERWEAR",
        list: [
          "Innerwear Collections",
          "AISism",
          "Undershirts",
          "Underwear",
          "HEATTECH",
          "Leggings & Tights",
          "Socks",
        ],
      },
    ],
  ],
  featured: [
    {
      title: "Featured",
      list: [
        "New Arrivals",
        "Limited Offer",
        "Comming Soon",
        "Featured News",
        "UT Graphic T-Shirts",
        "Styling Book",
        "About LifeWear",
      ],
    },
    {
      title: "Special collaboration",
      list: [
        "UNIQLO and JW ANDERSON",
        "+ J",
        "Uniqlo U",
        "UNIQLO x Theory",
        "Uniqlo and Mame Kurogouchi",
      ],
    },

    {
      title: "Browse",
      list: ["All Mens"],
    },
  ],
};

export const CategoriesKids = {
  columns: [
    [
      {
        title: "TOPS",
        list: [
          "Tops Colection",
          "T-Shirt",
          "UT(Graphic T-Shirts)",
          "Shirts & Blouses",
          "Formal Shirts",
          "Sweat Collections",
        ],
      },
      {
        title: "INNERWEAR",
        list: [
          "Innerwear Collections",
          "AISism",
          "Shorts",
          "Underwear",
          "Bras & Bra Top",
          "HEATTECH",
          "Leggings & Tights",
          "Socks",
        ],
      },
    ],
    [
      {
        title: "OUTERWEAR",
        list: ["Outeewear Collections", "Blouson & Hoodie", "Jackets & Coats"],
      },
      {
        title: "LOUNGEWEAR",
        list: ["Loungewear Colections", "Loungewear & Pajamas", "Room Shoes"],
      },
    ],
    [
      {
        title: "BOTTOMS",
        list: ["Bottoms Colections", "Pants", "Shorts", "Skirts"],
      },
      {
        title: "ACSESSORIES",
        list: ["Accessories Collections", "AIRism Marks"],
      },
    ],
    [
      {
        title: "DRESSES & JUMPSUITS",
        list: ["Dresses & Jumpsuits"],
      },
      {
        title: "SPORT UTILITY WEAR",
        list: ["Sport Utility Wear"],
      },
    ],
  ],
  featured: [
    {
      title: "Featured",
      list: [
        "New Arrivals",
        "Limited Offer",
        "Comming Soon",
        "Featured News",
        "UT Graphic T-Shirts",
        "Styling Book",
        "About LifeWear",
      ],
    },
    {
      title: "Special collaboration",
      list: ["Uniqlo U", "Special collaboration"],
    },
    {
      title: "Browse",
      list: ["All Kids"],
    },
  ],
};

export const CategoriesBaby = {
  columns: [
    [
      {
        title: "TODDLER (6 MONTHS - 5 YEARS)",
        list: [
          "Outerwear",
          "Tops",
          "UT(Graphic T-Shirts)",
          "Bottoms & Lengging",
          "Pajamas",
          "Cotton Innerwear",
          "AIRism",
          "Socks",
          "Accessories",
        ],
      },
    ],
    [
      {
        title: "NEWBORN (0-3 MONTHS)",
        list: ["Birth preparation items", "One-Pieces", "Accessories"],
      },
    ],
    [
      {
        title: "NEWBORN (3-24 MONTHS)",
        list: [
          "One-Pieces",
          "Bodysuits",
          "Tops",
          "Lenggings",
          "UT(Graphic T-shirts)",
          "AIRism",
          "Socks",
          "Accessories",
        ],
      },
    ],
  ],
  featured: [
    {
      title: "Featured",
      list: [
        "New Arrivals",
        "Limited Offer",
        "Comming Soon",
        "Featured News",
        "UT Graphic T-Shirts",
        "Styling Book",
        "About LifeWear",
      ],
    },
    {
      title: "Special collaboration",
      list: ["Special Collaborations"],
    },
    {
      title: "Browse",
      list: ["All Baby"],
    },
  ],
};

export const ProductsData = [
  {
    id: 450322,
    name: "MEN Dry-EX Crew Neck Short Sleeve T-Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450322/item/goods_69_450322.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450322/sub/goods_450322_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450322/sub/goods_450322_sub26.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/450322/sub/goods_450322_sub25.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 399000,
    priceLimited: 391000,
    desc: "Performance shirt designed for cool comfort. Perfect for sports.",
    rating: 5,
    review: 2,
    overview: [
      "- Ergonomic design includes breathable mesh knit fabric in areas where heat and sweat tend to build up.",
      "- Side seams removed to minimize skin contact.",
    ],
    materials: [
      "Product ID 450322",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Polyester",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 449017,
    name: "MEN Dry-EX Crew Neck Short Sleeve T-Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/449017/item/vngoods_03_449017.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/449017/sub/vngoods_449017_sub2.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/449017/sub/vngoods_449017_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/449017/sub/vngoods_449017_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/449017/sub/goods_449017_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/449017/sub/goods_449017_sub18.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XL",
    priceOriginal: 399000,
    priceLimited: 391000,
    desc: "Dries sweat quickly, leaving you feeling fresh and comfortable. Fold back the cuffs to show off the accent color stripes.",
    rating: 4.5,
    review: 32,
    overview: [
      "- Made of 20% recycled polyester.",
      "- Sweat-wicking DRY-EX technology, as worn by athletes.",
      "- Cool Touch yarn for an instant cooling sensation.",
      "- Ergonomic mesh hole design for increased breathability in areas prone to heat and sweat.",
      "- With odor control features.",
      "- No seams on the sides to reduce skin contact.",
      "- Raglan sleeves for ease of movement during sports.",
      "- Accented by a tonal color stripe on the inside of the cuffs.",
    ],
    materials: [
      "Product ID 449017",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "79% Polyester, 21% Nylon ( 27% Uses Recycled Polyester Fiber )",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle, Do not Dry Clean",
    ],
  },
  {
    id: 448596,
    name: "MEN Ultra Stretch Active Jogger Pants",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422967/item/vngoods_08_422967.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422967/sub/vngoods_422967_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422967/sub/vngoods_422967_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422967/sub/vngoods_422967_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/422967/sub/goods_422967_sub9.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 499000,
    priceLimited: 391000,
    desc: "Great functionality and streamlined silhouette. Perfect for playing sports or just lounging around.",
    rating: 4.5,
    review: 25,
    overview: [
      "- With quick-drying DRY technology.",
      "- Ultra-stretch material that's lightweight and stretches horizontally and vertically.",
      "- The updates for this season include a pattern around the crotch area for a more comfortable feel.",
      "- We have re-worked the fit of the waist in response to customer feedback.",
      "- It's a casual look with a tapered silhouette that is great for any occasion.",
      "- The material itself was adjusted to create a better color.",
    ],
    materials: [
      "Product ID 448596",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Polyester",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 447978,
    name: "WOMEN Stretch Pique Short Sleeve Polo Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422723/item/vngoods_10_422723.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422723/sub/vngoods_422723_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/422723/sub/vngoods_422723_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/422723/sub/goods_422723_sub18.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XXL",
    priceOriginal: 499000,
    priceLimited: 391000,
    desc: "Luxe Supima®cotton lends a premium look and feel. Comfortable stretch material moves with you.",
    rating: 5,
    review: 9,
    overview: [
      "- The outer layer is made from fine Supima®cotton, which has a high-end look thanks to its superior color-retention capability.",
      "- Quick-drying functionality means moisture like sweat dries almost instantly.",
      "- The updates for this season include a pattern around the crotch area for a more comfortable feel.",
      "- Stretch fabric allows for easy movement.",
      "- A beautiful cut showcases the high-quality texture of the fabric.",
    ],
    materials: [
      "Product ID 447978",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "Body: 77% Cotton, 20% Polyester, 3% Spandex/ Rib: 83% Cotton, 17% Polyester",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 446929,
    name: "MEN AIRism Cotton Set (Short Sleeve)",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446929/item/vngoods_69_446929.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446929/sub/vngoods_446929_sub3.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/446929/sub/goods_446929_sub14.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 499000,
    priceLimited: 391000,
    desc: "A sporty loungewear set in cool AIRism.",
    rating: 5,
    review: 1,
    overview: [
      "- The look of cotton with AIRism performance.",
      "- The stretchy fabric has a perfectly casual feel.",
      "- Sporty design with color block collar and raglan sleeves.",
    ],
    materials: [
      "Product ID 446929",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "71% Cotton, 25% Polyester, 4% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 445455,
    name: "WOMEN Linen Blend Open Collar Short Sleeve Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445455/item/vngoods_66_445455.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445455/sub/vngoods_445455_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445455/sub/vngoods_445455_sub2.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445455/sub/vngoods_445455_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445455/sub/vngoods_445455_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445455/sub/goods_445455_sub18.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XXL",
    priceOriginal: 499000,
    priceLimited: 489000,
    desc: "Smooth, comfortable fabric with a fresh feel. Ideal for laid-back styling.",
    rating: 4.5,
    review: 33,
    overview: [
      "- The smooth texture of rayon meets the cool feel of linen.",
      "- Sophisticated natural texture with a soft touch.",
      "- Breezy open collar design.",
      "- Boxy cut with a longer hem at the back.",
      "- Styles on its own or as a light outer layer.",
    ],
    materials: [
      "Product ID 445455",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "47% Rayon, 33% Linen, 20% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 444804,
    name: "KIDS Dry-EX Half Pants",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444804/item/vngoods_66_444804.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444804/sub/vngoods_444804_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444804/sub/vngoods_444804_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/444804/sub/goods_444804_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/444804/sub/goods_444804_sub18.jpg?width=1600&impolicy=quality_75",
    ],
    for: "KIDS",
    size: "4-5Y(110)-14Y(160)",
    priceOriginal: 249000,
    priceLimited: 244000,
    desc: "Quick-drying mesh helps keep kids feeling fresh. Relaxed half-length design.",
    rating: 4.5,
    review: 9,
    overview: [
      "- DRY-EX fabric dries sweat quickly.",
      "- With odor control and Cool Touch functions.",
      "- Made with recycled polyester.",
      "- The waistband is secured on the inside to prevent twisting.",
    ],
    materials: [
      "Product ID 444804",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "[03 GRAY, 66 BLUE] 80% Polyester, 20% Nylon ( 40% Uses Recycled Polyester Fiber )",
      "[09 BLACK] 80% Polyester, 20% Nylon ( 100% Uses Recycled Polyester Fiber )",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle, Do not Dry Clean",
    ],
  },
  {
    id: 441758,
    name: "MEN Cargo Jogger Pants",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441758/item/vngoods_08_441758.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441758/sub/vngoods_441758_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441758/sub/vngoods_441758_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441758/sub/vngoods_441758_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441758/sub/goods_441758_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441758/sub/goods_441758_sub11.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441758/sub/goods_441758_sub12.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441758/sub/goods_441758_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441758/sub/goods_441758_sub19.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 799000,
    priceLimited: 489000,
    desc: "Sleek jogger pants for an active style. Featuring traditional cargo pants details.",
    rating: 4.5,
    review: 31,
    overview: [
      "- Made with stretch fabric.",
      "- Dobby fabric for a casual look.",
      "- Cargo-style jogger pants add a modern twist to the traditional military design.",
      "- Slim-fit, tapered cut is perfect for jogger pants.",
      "- Comfortable easy waist design.",
    ],
    materials: [
      "Product ID 441758",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "98% Cotton, 2% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 446919,
    name: "MEN Denim Work Jacket",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446919001/item/vngoods_66_446919001.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446919001/sub/vngoods_446919001_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446919001/sub/vngoods_446919001_sub2.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446919001/sub/vngoods_446919001_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/446919001/sub/goods_446919001_sub10.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/446919001/sub/goods_446919001_sub13.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 999000,
    priceLimited: 980000,
    desc: "A classic denim jacket with a modern cut, design and practical details.",
    rating: 4.5,
    review: 32,
    overview: [
      "- Stretchy and comfortable denim material.",
      "- Made of a lighter denim than regular denim jackets, so it is lighter and more comfortable to wear.",
      "- Showcasing the authentic feel of denim.",
      "- Unisex design.",
      "- Based on a work jacket, but with a simple and modern design.",
      "- Practical details include two pockets at the chest and waist.",
      "- Perfect for urban, casual styling.",
    ],
    materials: [
      "Product ID 446919",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "[01] 98% Cotton, 2% Spandex [Other Colors] 99% Cotton, 1% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 446718,
    name: "GIRLS Smooth Cotton Frill Dress",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446718/item/vngoods_52_446718.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/446718/sub/vngoods_446718_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/446718/sub/goods_446718_sub13.jpg?width=1600&impolicy=quality_75",
    ],
    for: "KIDS",
    size: "4-5Y(110)-14Y(160)",
    priceOriginal: 399000,
    priceLimited: 391000,
    desc: "Adorable design with frills and gathers. Soft and comfortable to wear.",
    rating: 4.5,
    review: 12,
    overview: [
      "- Frills at the sleeves and gathers at the waist.",
      "- A gusset under the frilled sleeves provides coverage for the chest.",
      "- Knee length dress for easy movement.",
    ],
    materials: [
      "Product ID 446718",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 445894,
    name: "WOMEN Satin Pajamas (Short Sleeve)",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445894/item/vngoods_69_445894.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445894/sub/vngoods_445894_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445894/sub/vngoods_445894_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445894/sub/goods_445894_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445894/sub/goods_445894_sub11.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445894/sub/goods_445894_sub13.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XL",
    priceOriginal: 799000,
    priceLimited: 784000,
    desc: "Smooth fabric and a sophisticated sheen. Our pajamas are a wardrobe essential.",
    rating: 4.5,
    review: 33,
    overview: [
      "- Wrinkle-resistant.",
      "- Satin fabric with a glossy sheen and an elegant drape.",
      "- With handy pockets.",
      "- Short sleeve design with classic piping.",
    ],
    materials: [
      "Product ID 445894",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Polyester",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 445480,
    name: "WOMEN AIRism Plunging Bra Camisole",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445480/item/vngoods_09_445480.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445480/sub/vngoods_445480_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445480/sub/vngoods_445480_sub3.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445480/sub/vngoods_445480_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445480/sub/vngoods_445480_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445480/sub/goods_445480_sub11.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445480/sub/goods_445480_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445480/sub/goods_445480_sub14.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XXL",
    priceOriginal: 499000,
    priceLimited: 489000,
    desc: "Combines the comfortable feel of AIRism with an elegant design.",
    rating: 5,
    review: 102,
    overview: [
      "A collaboration item with Mame Kurogouchi, a Japanese fashion brand whose beauty of design to enhance every woman’s body is attracting attention all over the world.",
      "- Made with AIRism fabric.",
      "- An elegant cut with meticulously designed details, including exquisite shoulder straps with gold colored adjusters.",
    ],
    materials: [
      "Product ID 445480",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "Body: 78% Nylon, 22% Spandex/ Lining: 85% Nylon, 15% Spandex/",
      "Cup (Lớp Lót Trong): 87% Polyester, 13% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 444537,
    name: "WOMEN Straight Flare Long Pants",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444537/item/vngoods_35_444537.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444537/sub/vngoods_444537_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/444537/sub/vngoods_444537_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/444537/sub/goods_444537_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/444537/sub/goods_444537_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/444537/sub/goods_444537_sub20.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XL",
    priceOriginal: 799000,
    priceLimited: 784000,
    desc: "Cool natural fabric. Comfortable elastic waist.",
    rating: 4.5,
    review: 25,
    overview: [
      "- The fabric combines a crisp feel and a casual, pre-washed look.",
      "- These versatile pants stay opaque.",
    ],
    materials: [
      "Product ID 444537",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "97% Cotton, 3% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 445135,
    name: "WOMEN Cotton Blend Parka",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445135/item/vngoods_07_445135.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445135/sub/vngoods_445135_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445135/sub/goods_445135_sub10.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445135/sub/goods_445135_sub11.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445135/sub/goods_445135_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445135/sub/goods_445135_sub19.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "XS-XL",
    priceOriginal: 1299000,
    priceLimited: 1275000,
    desc: "With its relaxed cut and natural texture, this parka pairs well with any outfit.",
    rating: 4.5,
    review: 10,
    overview: [
      "- Durable water-repellent coating.",
      "- Densely woven, crisp fabric.",
      "- The cotton blend fabric has a natural texture. *Cotton blend fabric is not available in CN or RUS - Longer length pairs well with any bottoms.",
      "- Relaxed fit with dropped shoulders.",
      "- Versatile A-line cut.",
      "- Fly front design for a sophisticated look.",
      "- Hood stands up neatly.",
      "- Drawstrings at the waist and hem allow you to change the silhouette.",
      "- The fit of the cuffs can be adjusted.",
      "- A casual outer layer for any occasion.",
    ],
    materials: [
      "Product ID 445135",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "84% Polyester, 16% Cotton",
      "WASHING INSTRUCTIONS",
      "Hand wash cold",
    ],
  },
  {
    id: 434282,
    name: "BABIES NEWBORN Cotton Mesh Inner Short Sleeve Bodysuit 2 Pack",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/434282/item/goods_03_434282.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/434282/sub/goods_434282_sub18.jpg?width=1600&impolicy=quality_75",
    ],
    for: "BABY",
    size: "AGE6-12M(70)-AGE18-24M(90)",
    priceOriginal: 249000,
    priceLimited: 244000,
    desc: "Joy of Print is a London based independent print studio founded by the designer Cath Kidston as a new solo project, introducing a collection flowing with beauty and joy.",
    rating: 4.5,
    review: 9,
    overview: [
      "- 100% cotton is gentle on your baby's skin and provides comfort even when the they sweat.",
      "- Mesh has superior breathability.",
      "- Our sewing process is designed with your baby’s delicate skin mind.",
      "- Features plastic snap-closures for kids with metal allergies.",
      "- Color-contrasting thread around the collar and leg openings makes it easy to tell the inside from the outside.",
      "- The care label is on the outside.",
    ],
    materials: [
      "Product ID 434282",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 436774,
    name: "KIDS Twill Easy Shorts",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/436774/item/goods_32_436774.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/436774/sub/goods_436774_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/436774/sub/goods_436774_sub19.jpg?width=1600&impolicy=quality_75",
    ],
    for: "KIDS",
    size: "4-5Y(110)-14Y(160)",
    priceOriginal: 249000,
    priceLimited: 195000,
    desc: "Elastic waist allows easy movement. A versatile item for everyday wear.",
    rating: 4.5,
    review: 10,
    overview: [
      "- 100% cotton twill fabric.",
      "- Updated with an adjustable elastic waist.",
      "- Versatile colors.",
    ],
    materials: [
      "Product ID 436774",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 449621,
    name: "MEN Comfort Jacket",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/425422/item/vngoods_09_425422.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/425422/sub/vngoods_425422_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/425422/sub/vngoods_425422_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/425422/sub/goods_425422_sub12.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/425422/sub/goods_425422_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/425422/sub/goods_425422_sub14.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/425422/sub/goods_425422_sub17.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "S-XL",
    priceOriginal: 1499000,
    priceLimited: 1471000,
    desc: "Looks neat like a jacket, but feels soft and can be thrown on comfortably. Also easy to care for.",
    rating: 4.5,
    review: 32,
    overview: [
      "- The fit has been updated this season to be more relaxed around the body and shoulder area.",
      "- Made with elegant jersey material that is light, stretchy, and comfortable.",
      "- The inner side is smooth and silky, so it is easy to throw on over a shirt.",
      "- A versatile item that looks great with both casual and formal styles.",
      "- Wrinkle-resistant for easy care and cleaning.",
    ],
    materials: [
      "Product ID 449621",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "[09,69] Shell: 56% Cotton, 44% Polyester/ Lining: 100% Polyester [08]",
      "Shell: 71% Polyester, 29% Cotton/ Lining: 100% Polyester",
      "WASHING INSTRUCTIONS",
      "Hand wash cold",
    ],
  },
  {
    id: 447760,
    name: "WOMEN Flared Hem Short Sleeve T-Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/447760/item/vngoods_64_447760.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/447760/sub/vngoods_447760_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/447760/sub/vngoods_447760_sub2.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/447760/sub/vngoods_447760_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/447760/sub/vngoods_447760_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/447760/sub/goods_447760_sub12.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/447760/sub/goods_447760_sub14.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "S-L",
    priceOriginal: 499000,
    priceLimited: 489000,
    desc: "Contrasting fabrics and a flared hem for an iconic JWA style.",
    rating: 4.5,
    review: 9,
    overview: [
      "New LifeWear that combines UNIQLO’s focus on design, fit, fabric, and functionality with JW ANDERSON’s focus on traditional British apparel into innovative designs.",
      "- Distinctive JWA design combines cotton and glossy woven fabric.",
      "- Features a flowing hem with an elegant drape.",
    ],
    materials: [
      "Product ID 447760",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "Body: 100% Cotton/ Woven: 100% Polyester/ Rib: 63% Cotton, 37% Polyester",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 448263,
    name: "MEN Easy Care Stretch Slim Fit Long Sleeve Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/419002/item/goods_69_419002.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/419002/sub/goods_419002_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/419002/sub/goods_419002_sub19.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/419002/sub/goods_419002_sub22.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "M-L",
    priceOriginal: 686000,
    priceLimited: 588000,
    desc: "Excellent stretch for comfort. Our broadcloth shirt with a smooth, soft feel.",
    rating: 4.5,
    review: 29,
    overview: [
      "- Added Easy Care processing makes ironing a snap.",
      "- Made with stretchy material for remarkable comfort.",
      "- Designed for comfort, right down to the details.",
      "- Collar and sleeve interfacing is substantial yet soft.",
      "- Smaller collar accentuates the slim-fit cut.",
      "- Collar designed to look great with or without a tie.",
      "- Shoulders designed with curved angles for easy movement",
      "- Cut slightly looser in the shoulders to create an elegant drape.",
      "- Pocket designed for both style and practicality. Just the right size for an ID card or passport.",
      "- Versatile standard collar.",
      "- An all-purpose wardrobe essential.",
    ],
    materials: [
      "Product ID 448263",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "96% Cotton, 4% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 438856,
    name: "Single Strap Backpack",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/438856/item/goods_07_438856.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/438856/sub/goods_438856_sub3.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/438856/sub/goods_438856_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/438856/sub/goods_438856_sub19.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/438856/sub/goods_438856_sub22.jpg?width=1600&impolicy=quality_75",
    ],
    for: "UNISEX",
    size: "",
    priceOriginal: 499000,
    priceLimited: 489000,
    desc: "Now with a matte texture for easy styling. A handy bag for short trips.",
    rating: 4.5,
    review: 26,
    overview: [
      "- Water-repellent coating.",
      "- Coating has been added to both the inner and outer surfaces.",
      "- Nylon twill fabric with a distinctive texture.",
      "- Practical size with two-layer cushioned pockets.",
      "- Minimal design with a gusset for extra storage capacity.",
      "- Matching strap for easy styling.",
      "- Updated in a matte, cotton-like material.",
    ],
    materials: [
      "Product ID 438856",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "Shell: 100% Nylon/ Lining: Body: 100% Polyester/ Mesh: 100% Polyester/",
      "Tape: 100% Polyester",
      "Height: 17cm, Width: 26cm, Depth: 5cm",
      "WASHING INSTRUCTIONS",
      "Do not wash",
    ],
  },
  {
    id: 441742,
    name: "MEN Slim Fit Jeans (Damaged)",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441742/item/vngoods_65_441742.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441742/sub/vngoods_441742_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/441742/sub/vngoods_441742_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441742/sub/goods_441742_sub9.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441742/sub/goods_441742_sub11.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/441742/sub/goods_441742_sub13.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 999000,
    priceLimited: 980000,
    desc: "Vintage denim looks and a comfortable fit. Updated details for even greater comfort.",
    rating: 4.5,
    review: 9,
    overview: [
      "- Our new material features uneven thread and an indigo dye effect to give a more natural look.",
      "- Mid-rise waist for a comfortable fit",
      "- Comfort stretch denim combines a comfortable feel with a realistic worn-in look.",
      "- Vintage look jeans with natural fading and distressed effects developed at the Jeans Innovation Center.",
      "- Authentic vintage texture created using a process developed at the Jeans Innovation Center.",
      "- Our sustainable washing process uses 90％ less water.",
      "- We’ve adjusted the angles of the back pockets and positioned the front pockets slightly higher.",
      "- Sleek straight cut from waist to the ankles.",
      "- Carefully designed details, such as buttons, rivets, and stitch colors that add to the vintage look.",
      "- We’ve updated and enhanced our classic slim fit jeans",
      "- In response to customer feedback, we’ve made our jeans more stylish and comfortable.",
    ],
    materials: [
      "Product ID 441742",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "98% Cotton, 2% Spandex",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 445830,
    name: "MEN Louvre Museum UT (Short Sleeve Graphic T-Shirt)",
    img: [
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445830/item/goods_69_445830.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445830/sub/goods_445830_sub14.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445830/sub/goods_445830_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445830/sub/vngoods_445830_sub27.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XXL",
    priceOriginal: 399000,
    priceLimited: 244000,
    desc: "A second long-awaited collection with the Louvre! Collaboration with Peter Saville is realized again.",
    rating: 4.5,
    review: 7,
    overview: [
      "Musée du Louvre",
      "The masterpieces of Paris’ Louvre Museum, newly interpreted under the theme of “Art and Logic” by the renowned Peter Saville. Saville has visualized the composition after discovering the world famous works were known at the Louvre simply by their accession numbers and used this as a starting point to create his theme.",
      "Leonardo DA VINCI / Mona Lisa – Portrait of Lisa Gherardini, wife of Francesco del Giocondo",
      "© RMN-Grand Palais (Musée du Louvre) / Michel Urtado",
      "© PETER SAVILLE",
    ],
    materials: [
      "Product ID 445830",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold",
    ],
  },
  {
    id: 445174,
    name: "MEN Dry-EX Short Sleeve Polo Shirt",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445174/item/vngoods_66_445174.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445174/sub/vngoods_445174_sub6.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445174/sub/vngoods_445174_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445174/sub/goods_445174_sub10.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/445174/sub/goods_445174_sub18.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/445174/sub/vngoods_445174_sub24.jpg?width=1600&impolicy=quality_75",
    ],
    for: "MEN",
    size: "XS-XL",
    priceOriginal: 499000,
    priceLimited: 489000,
    desc: "Designed to keep you cool and comfortable. Perfect for sports.",
    rating: 4.5,
    review: 40,
    overview: [
      "- Ergonomic mesh design for increased breathability in areas prone to heat and sweat.",
      "- Pique-style fabric stays opaque.",
      "- No side seams for minimal skin contact.",
      "- Accent stripe on the collar.",
    ],
    materials: [
      "Product ID 445174",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "Body: 80% Polyester, 20% Nylon",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
  {
    id: 451541,
    name: "WOMEN Cotton Dobby Short Sleeve Belted Dress",
    img: [
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451541/item/vngoods_30_451541.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451541/sub/vngoods_451541_sub1.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451541/sub/vngoods_451541_sub7.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/vn/imagesgoods/451541/sub/vngoods_451541_sub8.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/451541/sub/goods_451541_sub12.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/451541/sub/goods_451541_sub13.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/451541/sub/goods_451541_sub14.jpg?width=1600&impolicy=quality_75",
      "https://image.uniqlo.com/UQ/ST3/AsianCommon/imagesgoods/451541/sub/goods_451541_sub17.jpg?width=1600&impolicy=quality_75",
    ],
    for: "WOMEN",
    size: "S-L",
    priceOriginal: 1299000,
    priceLimited: 1275000,
    desc: "An airy dress made with 100% cotton. Belted waist for more styling options.",
    rating: 5,
    review: 2,
    overview: [
      "From our collaboration with fashion designer Hana Tajima.",
      "- 100% cotton in a crisp, cool dobby weave.",
      "- The belted waist lets you adjust the silhouette.",
      "- Open-front design means it also styles as a light outer layer.",
      "- Roomy fit with gathers at the neckline.",
    ],
    materials: [
      "Product ID 451541",
      "Please note that this product may have different product ID, even if it is the same item.",
      "FABRIC DETAILS",
      "100% Cotton",
      "WASHING INSTRUCTIONS",
      "Machine wash cold, gentle cycle",
    ],
  },
];
