export const actionTypes = {
  ADD_TO_WISH_LIST: "ADD_TO_WISH_LIST",
  REMOVE_FROM_WISH_LIST: "REMOVE_FROM_WISH_LIST",
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_ITEM: "REMOVE_ITEM",
  INCREASE: "INCREASE",
  SET_QUANTITY: "SET_QUANTITY",
  CHECKOUT: "CHECKOUT",
  SEARCH: "SEARCH",
  SET_CART: "SET_CART",
  SET_WISH_LIST: "SET_WISH_LIST",
  GET_TOTALS: "GET_TOTALS",
  LOGOUT: "LOGOUT",
};
